

export const list = [
  { id: 1, category: "banana", name: "Item 1", text: "Text for item 1" },
  { id: 2, category: "apple", name: "Item 2", text: "Text for item 2" },
  { id: 3, category: "another", name: "Item 3", text: "Text for item 3" },
  { id: 4, category: "apple", name: "Item 4", text: "Text for item 4" },
  { id: 5, category: "third", name: "Item 5", text: "Text for item 5" },
  { id: 6, category: "banana", name: "Item 6", text: "Text for item 6" },
  { id: 7, category: "third", name: "Item 7", text: "Text for item 7" },
  { id: 8, category: "banana", name: "Item 8", text: "Text for item 8" },
  { id: 9, category: "apple", name: "Item 9", text: "Text for item 9" },
  { id: 10, category: "some", name: "Item 10", text: "Text for item 10" },
  { id: 11, category: "some", name: "Item 11", text: "Text for item 11" },
  { id: 12, category: "apple", name: "Item 12", text: "Text for item 12" },
  { id: 13, category: "some", name: "Item 13", text: "Text for item 13" },
  { id: 14, category: "banana", name: "Item 14", text: "Text for item 14" },
  { id: 15, category: "some", name: "Item 15", text: "Text for item 15" },
  { id: 16, category: "banana", name: "Item 16", text: "Text for item 16" },
  { id: 17, category: "another", name: "Item 17", text: "Text for item 17" },
  { id: 18, category: "another", name: "Item 18", text: "Text for item 18" },
  { id: 19, category: "third", name: "Item 19", text: "Text for item 19" },
  { id: 20, category: "another", name: "Item 20", text: "Text for item 20" },
  { id: 21, category: "banana", name: "Item 21", text: "Text for item 21" },
  { id: 22, category: "some", name: "Item 22", text: "Text for item 22" },
  { id: 23, category: "third", name: "Item 23", text: "Text for item 23" },
  { id: 24, category: "some", name: "Item 24", text: "Text for item 24" },
  { id: 25, category: "banana", name: "Item 25", text: "Text for item 25" },
  { id: 26, category: "third", name: "Item 26", text: "Text for item 26" },
  { id: 27, category: "third", name: "Item 27", text: "Text for item 27" },
  { id: 28, category: "apple", name: "Item 28", text: "Text for item 28" },
  { id: 29, category: "banana", name: "Item 29", text: "Text for item 29" },
  { id: 30, category: "third", name: "Item 30", text: "Text for item 30" },
  { id: 31, category: "apple", name: "Item 31", text: "Text for item 31" },
  { id: 32, category: "some", name: "Item 32", text: "Text for item 32" },
  { id: 33, category: "banana", name: "Item 33", text: "Text for item 33" },
  { id: 34, category: "another", name: "Item 34", text: "Text for item 34" },
  { id: 35, category: "apple", name: "Item 35", text: "Text for item 35" },
  { id: 36, category: "third", name: "Item 36", text: "Text for item 36" },
  { id: 37, category: "apple", name: "Item 37", text: "Text for item 37" },
  { id: 38, category: "banana", name: "Item 38", text: "Text for item 38" },
  { id: 39, category: "apple", name: "Item 39", text: "Text for item 39" },
  { id: 40, category: "banana", name: "Item 40", text: "Text for item 40" }
];
